Support self contained schemas using __MODULE__
[Closes #684]

Support using `import_types` using the `__MODULE__` special form.
According to #684, This was supported previously in 1.4, but since 1.5
it has been erroring out in compile time with the following:

```
== Compilation error in file lib/potion_web/schema.ex ==
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2

    The following arguments were given to :elixir_aliases.do_concat/2:

        # 1
        [{:__MODULE__, [line: 56], nil}, :Types]

        # 2
        "Elixir"

    lib/absinthe/schema/notation.ex:1454: Absinthe.Schema.Notation.do_import_types/3
    expanding macro: Absinthe.Schema.Notation.import_types/1
    lib/potion_web/schema.ex:56: PotionWeb.Schema (module)
```